### PR TITLE
CS bonus

### LINKED ISSUE #16: High CS Buff
cs8 6* are incredibly harder than cs4 9* so possibly base a buff on cs based on hit radius (i.e the lower the radius is the higher the buff is)

### PR DESCRIPTION
**Pull request by kittsun**
Closes #16 
This addition gives maps that are precise and tricky to aim more performance points. The base CS is 6, and the bonus pp scales up as the CS scales up.

### CODE REVIEW

**Comment by tsunyoku** [comment]
ty :)

**Comment by tsunyoku** [comment]
one more thing, you need to check if we are on relax or not before applying buff

**Comment by tsunyoku** [comment]
ty, merging :p

**Comment by kittsun** [comment]
np babes love you x

**Pull request merged**
